version: '3.8'

services:
  pocketbase:
    build: pocketbase
    container_name: database
    volumes:
      - pocketbase-data:/pb
      - ./pocketbase/pb_migrations:/pb/pb_migrations
    ports:
      - '8080:8080'
    networks:
      default:

  next:
    image: node:18
    container_name: next
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`localhost`)
      - traefik.http.services.web.loadbalancer.server.port=3000
      - traefik.http.routers.web.service=web
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    command: sh -c "npm install && npm run dev"
    networks:
      default:
      frontend:    

  ingress:
    container_name: ingress
    image: traefik:v2.7
    command:
      - --api.dashboard=true
      - --api.insecure=true # remove once https is configured?
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=frontend
      - --providers.docker.network=default
      - --providers.docker.watch=true
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
    ports:
      - '80:80'
      - '8081:8080'
    volumes:
      - traefik-state:/etc/traefik/state
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      frontend:
      default:

networks:
  frontend:
    name: frontend
    external: true

volumes:
  traefik-state:
    driver: local
  pocketbase-data:
    driver: local